### ISSUE TITLE
Where can I find the whole project？It is useful and interesting，THX！

### ISSUE THREAD

**Issue by scarrrr316** [pauls-3d-things/smd-soldering-station#1]
same as title

**Comment by uvwxy** [comment]
I haven't had the motivation to write it yet.

You can find more info here:
https://www.youtube.com/watch?v=39ij7f1OWtc

and here:
https://www.makermoekoe.net/post/maker-moekoe-s-kind-of-soldering-iron

And I used:
- 2x Heatplates: https://www.aliexpress.com/item/32974173898.html
- 1x SSR: https://www.aliexpress.com/item/32706812752.html
- 1x TTGO ESP8266 OLED Controller: https://www.aliexpress.com/item/32854542718.html

**Comment by scarrrr316** [comment]
> I haven't had the motivation to write it yet.
> 
> You can find more info here:
> https://www.youtube.com/watch?v=39ij7f1OWtc
> 
> and here:
> https://www.makermoekoe.net/post/maker-moekoe-s-kind-of-soldering-iron
> 
> And I used:
> 
> * 2x Heatplates: https://www.aliexpress.com/item/32974173898.html
> * 1x SSR: https://www.aliexpress.com/item/32706812752.html
> * 1x TTGO ESP8266 OLED Controller: https://www.aliexpress.com/item/32854542718.html

oh THX，did you draw any schematic？If yes ，can you send it to me？If no，It's ok. Thankyou for your reply

**Comment by scarrrr316** [comment]
oh god ，，，，it is hard for me to read the code that have multi files ，why dont combine them together ，haha，it look complex.
thx for your project
